branches:
  only:
    - develop

language: node_js

sudo: false

node_js: stable

cache:
  directories:
  - node_modules

before_install:
- git config --global user.name "inizio"
- git config --global user.email "digit4free@gmail.com"
- git clone --branch master https://github.com/IniZio/inizio.github.io.git dist

install:
- npm install

script:
  - npm run build

after_script:
- cd dist
- echo "inizio.github.io" > CNAME
- git add --all .
- git commit --message "automatically update from travis-ci"
- git push "https://${GH_TOKEN}@${GH_REF}" master:master --quiet
